-- 0093_add_bom_secondary_vendor
--
-- Adds the "secondary vendor" Bill of Materials rule: a part bought from one vendor
-- that also needs its own line, at its own cost, on a SECOND vendor's sheet (e.g.
-- sent out for powder coating after being purchased raw) — additive to the part's
-- own vendor line, unlike the existing free-issue rule, which redirects it. All
-- additive and backward-compatible — no existing column, table, or row is touched.
--
-- Hand-written rather than generated by `pnpm db:new`: the Neon database this
-- environment's DATABASE_URL points at was unreachable (account/project quota
-- exceeded) at the time this migration was authored, so the usual `prisma migrate
-- diff` step could not run. Written by hand to the same guarded shape every other
-- migration in this repo uses (see docs/database-migrations.md) — verify with
-- `pnpm db:drift` after applying, same as any other migration.
--
-- Statements are guarded so a re-run is harmless: migrate-deploy.mjs runs on
-- every deploy and a half-applied migration must be repairable by running it again.

-- AlterTable
ALTER TABLE "Sku" ADD COLUMN IF NOT EXISTS "secondaryVendor" TEXT;
ALTER TABLE "Sku" ADD COLUMN IF NOT EXISTS "secondaryVendorCostMinor" INTEGER;

-- AlterTable
ALTER TABLE "ProcurementLine" ADD COLUMN IF NOT EXISTS "secondaryOfSku" TEXT;
